backend:
  name: git-gateway
  branch: main 

media_folder: "src/assets/images" 
public_folder: "/assets/images"

collections:
  - name: "teams"
    label: "F1 Teams"
    folder: "src/_data/teams" 
    create: true
    extension: "json"
    format: "json"
    slug: "{{name}}"
    fields:
      - { label: "Team Name", name: "name", widget: "string" }
      - { label: "Base", name: "base", widget: "string" }
      - { label: "Hex Color", name: "color", widget: "color" }
      - label: "Drivers"
        name: "drivers"
        widget: "list"
        summary: "{{driver}}"
        field: { label: "Driver Name", name: "driver", widget: "string" }
      - { label: "Description", name: "desc", widget: "text" }